version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: stationSki
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: 47746/devopsproject-production-e2e-pipeline:latest
    container_name: station_ski_app
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/stationSki?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - database

volumes:
  db_data:
