version: '3.8'

services:
  app:
    image: 47746/devopsproject-production-e2e-pipeline:latest
    restart: always
    build: .
    ports:
      - "8089:8089"
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: root  
      MYSQL_PORT: 3306

  database:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: stationSki
      MYSQL_ROOT_PASSWORD: root  

volumes:
  mysql-data:
