version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: stationSki
    ports:
      - "3306:3306"

  app:
    build: .
    image: majjmajj/myskiproject:latest
    ports:
      - "8089:8089"
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
