apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  # Ajoutez ici toute configuration non sensible pour votre application
    spring.datasource.url: "jdbc:mysql://mysql:3306/stationSki?createDatabaseIfNotExist=true"
    spring.datasource.username: "root"
    spring.datasource.password: "${MYSQL_ROOT_PASSWORD}"
    spring.jpa.show-sql: "true"
    spring.jpa.hibernate.ddl-auto: "update"
    spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"

