apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi    # Spécifiez le minimum requis
    limits:
      storage: 2Gi    # Spécifiez la limite de stockage maximale
