apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: gestionstationacr.azurecr.io/abm026/gestion-station-ski:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-configmap
      imagePullSecrets:
        - name: acr-credentials