apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  labels:
    app: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      automountServiceAccountToken: false
      containers:
        - name: springboot-app
          image: "oussamacontainerregistry01.azurecr.io/gammoudioussama/skier-app:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8089

          env :
            - name: MYSQL_DB_USER  # Setting Database username
              value: root
            - name: MYSQL_PASSWORD # Setting Database password
              value: root

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
