apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      automountServiceAccountToken: false  # Désactive le montement automatique du service account
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
              - name: MYSQL_ROOT_PASSWORD
                value: root
              - name: MYSQL_DATABASE
                value: stationSki

          resources:
            requests:
              memory: "1Gi"   # Mémoire minimum pour MySQL
              cpu: "500m"     # CPU minimum pour MySQL
            limits:
              memory: "2Gi"   # Limite de mémoire maximale
              cpu: "1000m"    # Limite de CPU maximale
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql  # Répertoire où MySQL stocke ses données
      volumes:
        - name: mysql-storage
          emptyDir: {}  # Utilisation de emptyDir au lieu de PV/PVC
